### ISSUE TITLE
Empty category inside a forum hides said parent forum

### ISSUE THREAD

**Issue by vendethiel** [MightyGorgon/icy_phoenix#119] opened 2016-01-20 21:19 UTC
If I have a category > forum (when you install IP, it's "Test Forum 1"), and I append a new, empty category to said forum ( http://i.imgur.com/AoiizKi.png ).

The forum itself ("Test Forum 1") doesn't show up on the forum.php page anymore.

But if I add a forum child to the nested category, it goes back to normal.

**Comment by MightyGorgon** [comment] 2016-01-26 09:40
**Cat 1 -> Forum 1 -> Cat 2**: __Forum 1__ disappears 
**Cat 1 -> Forum 1 -> Cat 2 -> Forum 2**: __Forum 1__ is back

That's right?

So the issue is when having an empty category?

**Comment by vendethiel** [comment] 2016-01-26 10:00
yes, that's correct

**Comment by MightyGorgon** [comment] 2016-01-26 10:18
I think because if you add an empty cat, then the forum is treated as a cat itself...

It requires some time to look into... I will when I have at least an hour, since it isn't so important as a bug... I think it's quite rare than someone will just attach an empty cat to a forum.

**Comment by vendethiel** [comment] 2016-01-26 10:23
Right, it is. I just don't want to look at it because I don't understand the code, it just makes my head hurt... 
Although I know last time I looked at it was before you merged categories&forums, maybe it's clearer now.

**Comment by MightyGorgon** [comment] 2016-02-02 19:07
I won't fix this for now as it is a very special case.

I may fix it in the future.

**Closed** 2017-08-18 21:13 UTC
Labels: Bug
