### ISSUE TITLE
FAQ Issue

### ISSUE THREAD

**Issue by MWE001** [MightyGorgon/icy_phoenix#130] opened 2016-09-14 01:05 UTC
If you go to the FAQ, You can click on the + next to any topic to open it up to see the child topic.  Once the children are shown, you can once again click one of those to see the topic. Once the child is open, it will not close, You can open other child topics, but they will not close either. It will only close if you click the - next to the parent. I tried on IE, Firefox and Chrome.

![faq](https://cloud.githubusercontent.com/assets/2566493/18496681/75a35830-79ed-11e6-8357-63de80915a0a.jpg)

**Comment by MWE001** [comment] 2016-09-14 02:39
that screenshot really don't tell you nothing  lol sorry I'm a dork like that. Here take a look at this. I put CamStudio to use.

https://youtu.be/LkQW_84T7Po

**Comment by MightyGorgon** [comment] 2016-09-19 22:24
Those stuff has to be rewritten with jQuery... @vendethiel do you want to try? :-)

**Comment by vendethiel** [comment] 2016-09-23 23:15
The issue is a bit misleading. Only the `[-]` itself doesn't work – clicking the child's item name *will* close it.

**Comment by vendethiel** [comment] 2016-09-23 23:27
Is the "save preferences to cookie" thing important? I'm not sure anyone cares about saving their FAQ menus to cookies...

**Comment by vendethiel** [comment] 2016-09-23 23:31
I rewrote it without cookies in 10 lines of jQuery...

**Comment by vendethiel** [comment] 2016-09-23 23:44
And for the issue at hand – no clue. Seems to be a CSS issue: the image is not part of the element. But only with the class `minimise`...

**Closed** 2016-11-02 07:00 UTC
Labels: Bug
